services:
  - type: web
    name: clear-cut
    env: docker
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: OMP_NUM_THREADS
        value: "1"
      - key: MKL_NUM_THREADS
        value: "1"
